/tmp/tmp4t8nig73/test.c:1:10: fatal error: ndbm.h: No such file or directory
 #include <ndbm.h>
          ^~~~~~~~
compilation terminated.
/tmp/tmpjh465u3k/undef.c:1:10: fatal error: ndbm.h: No such file or directory
 #include <ndbm.h>
          ^~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "linknamespace.py", line 217, in <module>
    main()
  File "linknamespace.py", line 176, in main
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gcc -I../include  -I/home/mritunjya/rooms/cryptography/crypto-hack/crackmes-one/glibc-2.34/build  -I../sysdeps/unix/sysv/linux/x86_64/64  -I../sysdeps/unix/sysv/linux/x86_64  -I../sysdeps/unix/sysv/linux/x86/include -I../sysdeps/unix/sysv/linux/x86  -I../sysdeps/x86/nptl  -I../sysdeps/unix/sysv/linux/wordsize-64  -I../sysdeps/x86_64/nptl  -I../sysdeps/unix/sysv/linux/include -I../sysdeps/unix/sysv/linux  -I../sysdeps/nptl  -I../sysdeps/pthread  -I../sysdeps/gnu  -I../sysdeps/unix/inet  -I../sysdeps/unix/sysv  -I../sysdeps/unix/x86_64  -I../sysdeps/unix  -I../sysdeps/posix  -I../sysdeps/x86_64/64  -I../sysdeps/x86_64/fpu/multiarch  -I../sysdeps/x86_64/fpu  -I../sysdeps/x86/fpu  -I../sysdeps/x86_64/multiarch  -I../sysdeps/x86_64  -I../sysdeps/x86/include -I../sysdeps/x86  -I../sysdeps/ieee754/float128  -I../sysdeps/ieee754/ldbl-96/include -I../sysdeps/ieee754/ldbl-96  -I../sysdeps/ieee754/dbl-64  -I../sysdeps/ieee754/flt-32  -I../sysdeps/wordsize-64  -I../sysdeps/ieee754  -I../sysdeps/generic  -I.. -D_ISOMAC -ansi -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -c /tmp/tmpjh465u3k/undef.c -o /tmp/tmpjh465u3k/undef.o' returned non-zero exit status 1.
